### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by griffinbird** [dgageot/dockercon16#2]
Hi,

I am using windows 10 with the Docker Windows Beta. After running your commands I cannot browse to localhost but when I browse to Docker/ I receive the following:

403 Forbidden
nginx/1.11.1

**Comment by ghost** [comment]
@wiziah I had the same issue and resolved it by enabling the Shared Drives capability in the docker settings.

**Comment by griffinbird** [comment]
@JargoonPard Thanks.. that did the trick.
