### ISSUE TITLE
Why localhost:30000

### ISSUE THREAD

**Issue by llitfkitfk** [dgageot/dockercon16#3]
I use docker deploy dockercon16

inside the docker for mac  ls /port :  tcp:0.0.0.0:30000:tcp:172.19.0.2:30000 

why the port is 30000?

**Comment by dgageot** [comment]
@llitfkitfk This is a bug in 1.12RC2. Must have been fixed in 1.12RC3

**Comment by llitfkitfk** [comment]
@dgageot I try to redeploy the dockercon in 1.12RC3(docker for mac)

still using localhost:30000

**Comment by llitfkitfk** [comment]
https://docs.docker.com/engine/swarm/key-concepts/#load-balancing
